### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by oleid** [dfyz/osm-renderer#3]
Thanks for this cool project! I'm intending to write a rust based desktop and/or mobile map viewer and was considering re-using some of your drawing code, if possible. And thus, I was wondering what license it has.

**Comment by dfyz** [comment]
Hi! I didn't intend for this to go beyond a pet project, so I never bothered with a license. I guess it's time to choose one. I'm leaning towards the [MIT License](https://choosealicense.com/licenses/mit/), since it is about as permissive as it can get. Are you OK with this license?

**Comment by oleid** [comment]
Hi! Sure, perfectly okay. I'm not sure, yet, if what I'm intending to do will go beyond a pet project. But in any case, if I was going to use other people's source code, I'd like to attribute it properly :)

**Comment by dfyz** [comment]
I specified the license in c8efdcd. Feel free to use the code. :)
