### ISSUE TITLE
Parsing inputfile fails due to "Unexpectedend of stream: still inside the root element"

### ISSUE THREAD

**Issue by IgnoreWarnings** [dfyz/osm-renderer#8]
**Problem Description**
Parsing inputfile fails. See full output below.

**Actions taken**
Tried different map files (all .osm).

**Steps to reproduce:**
Cloned project from Master branch
Following the [ import description ](https://github.com/dfyz/osm-renderer/blob/master/README.md)

1. cargo run --release --bin importer /.../maps/someMap.osm /.../maps/someMap.bin

`    Finished release [optimized + debuginfo] target(s) in 0.12s
     Running "target/release/importer /.../maps/someMap.osm /.../maps/someMap.bin"
Importing OSM data from /.../maps/someMap.osm
Parsing XML
Got 99998 nodes, 0 ways and 0 multipolygon relations so far
Got 199998 nodes, 0 ways and 0 multipolygon relations so far
Got 299998 nodes, 0 ways and 0 multipolygon relations so far
Got 399998 nodes, 0 ways and 0 multipolygon relations so far
Got 499998 nodes, 0 ways and 0 multipolygon relations so far
Got 599998 nodes, 0 ways and 0 multipolygon relations so far
Got 699998 nodes, 0 ways and 0 multipolygon relations so far
Got 799998 nodes, 0 ways and 0 multipolygon relations so far
Got 899998 nodes, 0 ways and 0 multipolygon relations so far
Got 999998 nodes, 0 ways and 0 multipolygon relations so far
Got 1099998 nodes, 0 ways and 0 multipolygon relations so far
Got 1199998 nodes, 0 ways and 0 multipolygon relations so far
Got 1299998 nodes, 0 ways and 0 multipolygon relations so far
Got 1399998 nodes, 0 ways and 0 multipolygon relations so far
Got 1499998 nodes, 0 ways and 0 multipolygon relations so far
Got 1599998 nodes, 0 ways and 0 multipolygon relations so far
Got 1699998 nodes, 0 ways and 0 multipolygon relations so far
Got 1799998 nodes, 0 ways and 0 multipolygon relations so far
Got 1899998 nodes, 0 ways and 0 multipolygon relations so far
Failed to parse the input file
2547829:37 Unexpected end of stream: still inside the root element`

**Comment by dfyz** [comment]
Is there any way to take a look at one of these map files? Judging from the error, it really looks like the `.osm` file you use is corrupted (my guess would be some sort of truncation in the middle). Since you say you tried different files, this is either a systematic corruption (e.g., you download the maps from a server that serves broken `.osm` files), or a really obscure bug in the renderer, which triggers on your side for some reason. It's really hard to tell without an example map I can try on my side.

Just to be sure, I just tried to import and render a random map (downloaded from [here](https://download.geofabrik.de/europe/serbia.html)). I don't see any problems with either import or rendering:
```
> cargo run --release --bin importer /.../maps/serbia-latest.osm /.../maps/serbia-latest.bin
Importing OSM data from /.../maps/serbia-latest.osm
Parsing XML
Got 99998 nodes, 0 ways and 0 multipolygon relations so far
Got 199998 nodes, 0 ways and 0 multipolygon relations so far
...
Got 20158111 nodes, 1857621 ways and 20541 multipolygon relations so far
Converting geodata to internal format
Successfully imported OSM data to /.../maps/serbia-latest.bin
> cargo run --release --bin renderer city.conf
    Finished release [optimized + debuginfo] target(s) in 0.01s
     Running `target/release/renderer city.conf`
```

**Comment by IgnoreWarnings** [comment]
The mapfile you proposed gives me the same error.

**Comment by IgnoreWarnings** [comment]
For now on i suggest using the mapfile you provided for further investigation, since it is known working on your system.

**Comment by IgnoreWarnings** [comment]
I inspected the mapfile and it looks broken. Let me look into this.

**Comment by IgnoreWarnings** [comment]
The problem was caused by corrupt mapfiles due to a bug in my download and extraction program.
